export const resumeItems = [
  {
    title: "Fullstack Web Developer",
    org: "Dakota Fabro Dev - Freelance",
    logo: "https://i.imgur.com/lW20ViD.png",
    date: "2022 to Present",
    current: true,
    location: "Los Angeles, CA",
    skills: [
      "Front-End Development",
      "Back-End Development",
      "Remote Collaboration",
      "UX/UI Design",
      "Building Positive Client Rapport",
    ],
    duties: [
      "Wireframe, design, build, and deploy sites based on client needs and pain points using frontend technologies such as ReactJS, HTML, JS, CSS, and CSS libraries",
      "Ensure security, maintainability, and cloud backups using backend technologies such as Node.js, Express.js, Firebase, and/or PostgreSQL depending on client needs",
      "Maintain positive working relationships with clientele in need of frontend, backend, and fullstack web development services",
      "Ensure transparency of workflow by logging working hours, providing clients with frequent updates, and fostering a client/contractor relationship that creates an organic and collaborative design process",
    ],
  },
  {
    title: "Software Engineer",
    org: "Fullstack Academy",
    logo: "https://i.imgur.com/UYRXdcB.jpg",
    date: "2021 to 2022",
    current: false,
    location: "New York, NY",
    skills: [
      "Fullstack Web Development",
      "Test Driven Development",
      "Remote Collaboration",
      "Git",
    ],
    duties: [
      "Collaborated remotely with software engineering teams to build fullstack applications using the PERN (PostgreSQL, Express.js, React, Node.js) & FERN (Firebase, Express.js, React, Node.js) stacks",
      "Implemented online weekly “React Parties” where software devs who needed extra support would attend to clarify React concepts and/or project implementations",
      "Coordinated and led various group projects by building and monitoring a project timeline to ensure tasks were appropriately delegated, team members felt supported, and deadlines were met in a timely manner without sacrificing product quality",
    ],
  },
  {
    title: "Frontend Developer & Educator",
    org: "GENESIS STEAM",
    logo: "https://i.imgur.com/5wXjXFn.png",
    date: "2021 to 2022",
    current: false,
    location: "Los Angeles, CA",
    skills: [
      "Project Management",
      "Front-End Development",
      "UX/UI Design",
      "Creating Virtual Spaces",
    ],
    duties: [
      "Developed and designed an online resource website using ReactJS  used across Los Angeles Unified School District (LAUSD)",
      "Rebuilt and revitalized the GENESIS STEAM program and delivered to over 1000 K-12 LAUSD students after the organization had been closed for over a year due to COVID-19",
      "Developed standardized systems to manage the physical GENESIS Innovation Lab including maintaining inventory of education supplies, managing all technology and equipment, overseeing all aspects of the Lab",
      "Developed internal professional development materials to foster positive working relationships and healthy workplace boundaries",
      "Worked collaboratively to align GENESIS STEAM curriculum with CA State Standards and UN Global Goals",
      "Created educational programming tools to ensure streamlined program planning as well as learning outcome metrics collection",
    ],
  },
  {
    title: "K8 Educator",
    org: "Allegiance STEAM Academy & iEmpire Academy",
    logo: "https://i.imgur.com/Xsd54KH.png",
    date: "2018 to 2021",
    current: false,
    location: "Chino, CA / San Bernardino, CA",
    skills: [
      "User/Learner Differenatiation",
      "Teaching/Coaching",
      "Classroom Management",
      "Culturally Responsive Pedagogy",
    ],
    duties: [
      "Closely tracked student progress through formative and summative student data with learning experiences by utilizing user experience research techniques (usability, accessibility, findability, and credibility) to ensure learning outcomes",
      "Collaborated with teaching teams to improve teaching workflow and learning outcomes through observation, feedback, and continual improvement",
      "Acted as technology consultant to educators and staff on school campus to ensure educators and staff were able to streamline their teaching and workflow to maximize learning outcomes in a virtual classroom setting",
      "Utilized G Suite educational apps to deliver student-centered, innovative, and real-world applicable units of study",
      "Manage classroom within a restorative justice and socio-emotional framework",
      "Create practical, critical, socially-aware, and culturally-responsive units of study in which students grapple with various Depths of Knowledge",
    ],
  },
  {
    title: "Photographer",
    org: "Dakota Cheyenne Photography",
    logo: "https://i.imgur.com/YYesDih.png",
    date: "2015 to Present",
    current: true,
    location: "Claremont, CA",
    skills: [
      "Adobe Creative Suite",
      "Photo Editing",
      "Customer Service",
      "Clientele Relationship Building",
    ],
    duties: [
      "Specialize in weddings, events, professional headshots, boudoir, and photojournalism",
      "Utilize Adobe Creative Suite (Photoshop CC, Lightroom, Spark, etc.) to professionally edit, enhance, and process RAW photo files and video content",
      "Manage multiple email servers and social network channels to effectively market services and products to wide audiences",
      "Manage and track invoices, contracts, and other correspondence between clients and prospects",
      "Maintain and monitor month-to-month revenue while meticulously keeping track of receipts, payments, and cash flow to ensure robust and sound financial health of the business",
    ],
  },
];
